# Generated by Django 5.0.3 on 2024-05-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_siblingship_siblings_cannot_be_the_same_person"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="partnership",
            constraint=models.CheckConstraint(
                check=models.Q(("person", models.F("partner")), _negated=True),
                name="partners_cannot_be_the_same_person",
            ),
        ),
    ]
