# Generated by Django 5.0.3 on 2024-05-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_partnership_partners_cannot_be_the_same_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siblingship",
            options={"ordering": ["person", "sibling"]},
        ),
        migrations.RemoveConstraint(
            model_name="siblingship",
            name="unique_siblingship",
        ),
        migrations.RemoveConstraint(
            model_name="siblingship",
            name="siblings_cannot_be_the_same_person",
        ),
        migrations.RenameField(
            model_name="siblingship",
            old_name="from_person",
            new_name="person",
        ),
        migrations.RenameField(
            model_name="siblingship",
            old_name="to_person",
            new_name="sibling",
        ),
        migrations.AddConstraint(
            model_name="siblingship",
            constraint=models.UniqueConstraint(
                fields=("person", "sibling"), name="unique_siblingship"
            ),
        ),
        migrations.AddConstraint(
            model_name="siblingship",
            constraint=models.CheckConstraint(
                check=models.Q(("person", models.F("sibling")), _negated=True),
                name="siblings_cannot_be_the_same_person",
            ),
        ),
    ]
