# Generated by Django 5.0.3 on 2024-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_person_genetic_parents_cannot_be_the_same_person_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='genetic_parents_cannot_be_the_same_person',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('genetic_mother', None), _negated=True), ('genetic_mother', models.F('genetic_father'))), name='genetic_parents_cannot_be_the_same_person'),
        ),
    ]
