# Generated by Django 5.0.3 on 2024-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0012_remove_person_genetic_parents_cannot_be_the_same_person_and_more",
        ),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="person",
            name="genetic_parents_cannot_be_the_same_person",
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("genetic_mother", models.F("genetic_father")), _negated=True
                ),
                name="genetic_parents_cannot_be_the_same_person",
            ),
        ),
    ]
